#!/usr/bin/env python3
"""Generate src/models/flexicubes_tables.hpp from the FlexiCubes DMC lookup tables."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from models.geometry.rep_3d.tables import dmc_table, num_vd_table, check_table

def fmt_int_list(name, rows, indent="    "):
    out = [f"{indent}// {name}"]
    for r in rows:
        out.append(indent + ", ".join(str(int(v)) for v in r) + ",")
    return "\n".join(out)

lines = []
lines.append("// Auto-generated by convert/gen_flexicubes_tables.py. Do not edit by hand.")
lines.append("// FlexiCubes DMC lookup tables (from NVIDIA FlexiCubes), used for the")
lines.append("// isosurface mesh-extraction step that runs in host C++ (no weights).")
lines.append("#pragma once")
lines.append("")
lines.append("#include <cstdint>")
lines.append("")
# dmc_table [256][4][7]
lines.append("static const int32_t DMC_TABLE[256][4][7] = {")
for c in range(256):
    lines.append("    {")
    for v in range(4):
        lines.append("        {" + ", ".join(str(int(x)) for x in dmc_table[c][v]) + "},")
    lines.append("    },")
lines.append("};")
lines.append("")
lines.append("static const int32_t NUM_VD_TABLE[256] = {")
lines.append(fmt_int_list("num_vd_table", [num_vd_table]))
lines.append("};")
lines.append("")
# check_table [256][5]
lines.append("static const int32_t CHECK_TABLE[256][5] = {")
for c in range(256):
    lines.append("    {" + ", ".join(str(int(x)) for x in check_table[c]) + "},")
lines.append("};")
lines.append("")
# constants
lines.append("// cube_corners_idx[c] = 2^c (MC corner occupancy bitmask)")
lines.append("static const int32_t CUBE_CORNERS_IDX[8] = {1, 2, 4, 8, 16, 32, 64, 128};")
lines.append("")
lines.append("// cube_edges[e*2], cube_edges[e*2+1]: the two corner indices of edge e (12 edges).")
lines.append("static const int32_t CUBE_EDGES[24] = {")
lines.append("    0, 1, 1, 5, 4, 5, 0, 4, 2, 3, 3, 7, 6, 7, 2, 6, 2, 0, 3, 1, 7, 5, 6, 4")
lines.append("};")
lines.append("")
lines.append("// quad_split_1 / quad_split_2: two triangle splits of a quad (0-1-2-3).")
lines.append("static const int32_t QUAD_SPLIT_1[6] = {0, 1, 2, 0, 2, 3};")
lines.append("static const int32_t QUAD_SPLIT_2[6] = {0, 1, 3, 3, 1, 2};")
lines.append("")

out_path = os.path.join(os.path.dirname(__file__), "..", "src", "models", "flexicubes_tables.hpp")
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out_path} ({os.path.getsize(out_path)} bytes)")